"use client";

/**
 * Analyst tab — "DEMO / LOCAL ANALYST" (blueprint Phase 11).
 *
 * Every answer is generated by lib/ai/explain.ts from the same deterministic
 * tool outputs shown on the Analysis/Compare/Financials tabs. There is no
 * language model in this MVP; the canned questions below are the ones the
 * blueprint names explicitly.
 */

import { useMemo, useState } from "react";
import type { MetricCategory, SiteAnalysis } from "@/types/domain";
import {
  explainBiggestRisk,
  explainDrivingAssumptions,
  explainRanking,
  explainWeightSensitivity,
  explainWhatWouldFlip,
} from "@/lib/ai/explain";
import { DEFAULT_WEIGHT_PROFILE } from "@/lib/scoring/weights";

interface Question {
  id: string;
  label: string;
  run: (analyses: SiteAnalysis[], selectedSiteId: string | null) => string;
  requiresMultiple?: boolean;
}

const QUESTIONS: Question[] = [
  {
    id: "why-ranks-first",
    label: "Why does the leading site currently rank first?",
    run: (analyses) => explainRanking(analyses),
  },
  {
    id: "biggest-risk",
    label: "What is the biggest risk for the selected site?",
    run: (analyses, selectedSiteId) => {
      const analysis = analyses.find((a) => a.site.id === selectedSiteId) ?? analyses[0];
      return analysis ? explainBiggestRisk(analysis) : "Select a site first.";
    },
  },
  {
    id: "driving-assumptions",
    label: "What assumptions drive the selected site's ranking?",
    run: (analyses, selectedSiteId) => {
      const analysis = analyses.find((a) => a.site.id === selectedSiteId) ?? analyses[0];
      return analysis ? explainDrivingAssumptions(analysis) : "Select a site first.";
    },
  },
  {
    id: "what-would-flip",
    label: "What would make the selected site win?",
    run: (analyses, selectedSiteId) => {
      if (!selectedSiteId) return "Select a site first.";
      return explainWhatWouldFlip(analyses, selectedSiteId);
    },
    requiresMultiple: true,
  },
  {
    id: "weight-sensitivity",
    label: "What if Accessibility were weighted 35%?",
    run: (analyses, selectedSiteId) => {
      const analysis = analyses.find((a) => a.site.id === selectedSiteId) ?? analyses[0];
      if (!analysis) return "Select a site first.";
      return explainWeightSensitivity(
        analysis,
        DEFAULT_WEIGHT_PROFILE,
        "accessibility" as MetricCategory,
        0.35,
      );
    },
  },
];

export function AnalystTab({
  analyses,
  selectedSiteId,
}: {
  analyses: SiteAnalysis[];
  selectedSiteId: string | null;
}) {
  const [answer, setAnswer] = useState<string | null>(null);
  const [activeQuestionId, setActiveQuestionId] = useState<string | null>(null);

  const canCompare = analyses.length > 1;

  const handleAsk = (question: Question) => {
    setActiveQuestionId(question.id);
    setAnswer(question.run(analyses, selectedSiteId));
  };

  const disabledReason = useMemo(() => {
    if (analyses.length === 0) return "Save and select a candidate site to ask the analyst.";
    return null;
  }, [analyses.length]);

  return (
    <div className="stack" style={{ maxWidth: 720 }}>
      <h2 style={{ fontSize: 16 }}>Analyst Assistant</h2>
      <p className="field-hint">
        Local, deterministic answers built from this session&apos;s analysis, scoring, and financial
        outputs — no external model, no invented numbers. Configuring a real model provider is a
        documented next step (see docs/ROADMAP.md); this assistant answers the same way either way.
      </p>

      {disabledReason ? (
        <div className="empty-state">{disabledReason}</div>
      ) : (
        <>
          {QUESTIONS.map((question) => (
            <button
              key={question.id}
              className="question-btn"
              disabled={question.requiresMultiple && !canCompare}
              onClick={() => handleAsk(question)}
            >
              {question.label}
              {question.requiresMultiple && !canCompare ? " (needs 2+ saved sites)" : ""}
            </button>
          ))}

          {answer && activeQuestionId ? (
            <div className="answer-card">
              <strong>{QUESTIONS.find((q) => q.id === activeQuestionId)?.label}</strong>
              <div style={{ marginTop: 8 }}>{answer}</div>
            </div>
          ) : null}
        </>
      )}
    </div>
  );
}
